export const RESUME_REQUEST = "RESUME_REQUEST";
export const RESUME_SUCCESS = "RESUME_SUCCESS";
export const RESUME_FAILURE = "RESUME_FAILURE";
export const RESUMELIST_REQUEST = "RESUMELIST_REQUEST";
export const RESUMELIST_SUCCESS = "RESUMELIST_SUCCESS";
export const RESUMELIST_FAILURE = "RESUMELIST_FAILURE";
export const ADD_RESUME = "ADD_RESUME";
export const DELETE_RESUME = "DELETE_RESUME";
